### ISSUE TITLE
hello，感谢你的开源

### ISSUE THREAD

**Issue by zplzpl** [feihua/simple-go#1]
Hi,

想咨询一下项目的情况

- 请问项目有继续的规划吗？
- 有做过gin-vue-admin的调研吗？
- 这是项目经验积累出来的吗？

**Comment by feihua** [comment]
首先感谢你的关注

1.项目会有继续的规划的,这二周会推一个新的版本上去,是仿一个电商系统,前端会出一个andorid的客户端



2.gin-vue-admin之前有一个这个版本的可以看下这个连接https://github.com/feihua/sys-ui,由于gin-vue-admin这个之前好久它没有更新了,所以才换Ant Design Pro,近来gin-vue-admin这个官方,重新更新了https://github.com/element-plus/element-plus这个,所以后续会适配一个这个版本的


3.因为所在的公司,现在是用微服务架构的,由之前的dubbo,spring cloud其中一些转go微服务,经验还在积累中,如果有兴趣的,可以加个微信:&nbsp;ABCzzzxx
